import React from 'react'
import Head from 'next/head'
import TabBar from '../tab-bar'

const Layout: React.FC = ({ children }: any) => (
  <div>
    <Head>
      <title>Clone Twitter</title>
      <meta name="Fake twitter" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <TabBar />
    {children}
  </div>
)

export default Layout
