import React from 'react'
import Head from 'next/head'
import TabBar from '../tab-bar'

const Layout = ({ children }: any) => {
  return (
    <div className='flex min-w-full min-h-full justify-center'>
      <Head>
        <title>Clone Twitter</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TabBar />
      {children}
    </div>
  )
}

export default Layout
